import './global.css';
import { grid } from './library/common/grid';
import FooterComponent from './library/footer/footer';
import NavbarComponent from './library/navbar/navbar';

export const metadata = {
    title: 'Welcome to voicify',
    description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <html lang="en">
                <body>
                    <NavbarComponent />
                    <main className={grid.container}>{children}</main>
                    <FooterComponent />
                </body>
            </html>
        </html>
    );
}
