import './global.css';
import NavbarComponent from './library/navbar/navbar';

export const metadata = {
    title: 'Welcome to voicify',
    description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>
                <NavbarComponent></NavbarComponent>
                <main>{children}</main>
            </body>
        </html>
    );
}
